# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1196ff7135696ed414ca0d7283300fa70d5533e29f00e0e2d99e8d77750af4f0745d5bcf228e8ebbd4fa4e8e86e7c26a43353e20c9c77517fa91bdf24568dc04

test:
  secret_key_base: fd94328c8deb1f1b5e0ceb5119099097ec776d3445c74e47c692f749a46a09a0303782542afee966167b869f61c07231fc1058c5ca84b9eb23dd01d48b1cae99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
